### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#12]
@P-Chang Would it be possible to hack the DLL to use some different fonts? Firstly it could fix the red X issue in japanese and secondly the current font is awful when turned to italics - so bad that we hardly ever use them.

**Comment by P-Chang** [comment]
http://www.mediafire.com/file/4u3f8q8y3wk5kqq/fonts.rar

This is font texture that is stored in UnityAssetBundle. And it is controlled by TextMeshPro.
And These image can't be showed correctly without graphic editor that have alpha map support.

If I make my own game in Unity with TextMeshPro, I might find the way to replace font.
But there are really few possibility.

**Comment by enumag** [comment]
Oh my. is this for real? I mean that's really not something we want to edit. At best someone might be able to add some chars to fix the red X issue but I consider even that unlikely.

However I don't see any italic characters there so I think italics are handled by the DLL just by skewing the characters when rendering them. Which means it might be possible to make it skew it a bit less than it does now. What do you think?

**Comment by P-Chang** [comment]
I didn't read console arcs yet. Could you show me specific part of using italic character?

**Comment by enumag** [comment]
I didn't read it yet either. And in those instances where it was used we removed it later because it looked just awful.

Anyway you can try italics by yourself. If I remember correctly you just need to add `<i>...</i>` to the text.

**Comment by P-Chang** [comment]
```
				if ((this.m_style & FontStyles.Italic) == FontStyles.Italic || (this.m_fontStyle & FontStyles.Italic) == FontStyles.Italic)
				{
					float num17 = (float)this.m_currentFontAsset.ItalicStyle * 0.01f;
					Vector3 b = new Vector3(num17 * ((this.m_cached_GlyphInfo.yOffset + this.m_padding + num16) * this.m_fontScale), 0f, 0f);
					Vector3 b2 = new Vector3(num17 * ((this.m_cached_GlyphInfo.yOffset - this.m_cached_GlyphInfo.height - this.m_padding - num16) * this.m_fontScale), 0f, 0f);
					vector += b;
					vector2 += b2;
					vector3 += b;
					vector4 += b2;
				}
```

Thanks, I probably found italic control. but **my Math score were always bad**, I can delete it, but I have no idea for less it.

I re-read this thread https://github.com/07th-mod/higurashi-console-arcs/issues/5

@DoctorDiablo use italic because he use italic as Japanese 『』
If you thought it was awful because character over-wrap "-", is it enough that change "Saeki-san" to "Saeki - san" ?

and I found TextMeshPro Tag list.
http://digitalnativestudios.com/textmeshpro/docs/rich-text/

We can use `<u>...</u>`

![20171119042312_1](https://user-images.githubusercontent.com/29869319/32984091-bb004d40-cce2-11e7-83ef-f30b257f2126.jpg)

Isn't it good enough ?

**Comment by P-Chang** [comment]
![20171119050845_1](https://user-images.githubusercontent.com/29869319/32984327-e6e826da-cce7-11e7-9566-7ac08a528587.jpg)
![20171119042400_1](https://user-images.githubusercontent.com/29869319/32984328-e8347cc8-cce7-11e7-9aaf-de3e28be48e3.jpg)

It was easy that I thought

**Comment by enumag** [comment]
The second screenshot is the original and the first is after your midification, right? Great job!

Italic is not supposed to be as distinctive as underline or bold so it's absolutely fine as it is in your first screenshot. I don't think underscore should be used in VN though.

You don't need to create new DLLs for all chapters because of this - it's minor and we will not need it immediately. Just add it when you will compile them because of other things.



@DoctorDiablo TL;DR for you: You can use italic in console arcs now when appropriate. @P-Chang managed to fix it so it won't look so awful in the next release.

**Comment by P-Chang** [comment]
It is right. first one is modded font.
This method have too many code, so if it could be replace to another tag, I prefer replace.

But if there are no good replacement until next update, I'll include it.

**Comment by enumag** [comment]
You mean you want to change for example `<u>...</u>` to be the new italic instead of it's original meaning?

**Comment by P-Chang** [comment]
If there are another good tag, yes. 
I just scare this most long code.

But my English knowledge is cheap. so, I also prefer original meaning and I'll leave it you and @DoctorDiablo .

However I can't understand translation rule of 『』 and italic.
I think 「」 and 『』 don't have big differences.

There are many tags, so I think there are way with leaving this code.
But if you want to use new italic font, I'll apply it in next update.

**Comment by enumag** [comment]
In my opinion just changing the current `<i>` would be best since we don't use it as it is anyway.

I don't understand the quoting rules either lol.
