### ISSUE TITLE
Issues with DRM-free Onikakushi (Assembly-CSharp.dll related?)

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/higurashi-patch-compiler#13]
Ping @P-Chang @enumag.
***

So, I don't know if you guys have been following our Discord (which has been actually a nice addition), but we recently got a lot of issues related to Onikakushi. The DRM-free version sold only by MangaGamer seems to be a version behind (4.6.5f1) while the Steam version is updated (5.2.2f1).

From what I could gather from this issue, installing the patch with the DRM-free version **does not boot the game at all**. It doesn't compile the *.mg files, just freezes at a black screen. My understanding of the issue is that we have some incompatibility with the Assembly-CSharp.dll. Here is the .dll from the DRM-free version: 
[Assembly-CSharp.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1565622/Assembly-CSharp.zip)

The current workaround for this issue is to make Onikakushi load into Watanagashi, something we also do with the console arcs.

@P-Chang, can you check the DRM-free dll and see if there's anything different from our version? I believe the issue lies with the outdated .exe, but since we don't have many options I want to make sure we cover every possibility.

**Comment by ItaloKnox** [comment]
By the way, the game closes itself if I put all the files from the Onikakushi Steam version there (didn't we have this issue before?). It only opens with ``steam_api.dll`` alongside the .exe. This is a less than ideal workaround, so I hope we find a way of fixing it.

[output_log.txt](https://github.com/07th-mod/higurashi-patch-compiler/files/1565638/output_log.txt)

**Comment by ItaloKnox** [comment]
I deleted the previous comment since it might only generate more confusion. Don't mind it if you read it first in your email. :P

**Comment by enumag** [comment]
Sorry I wasn't following discord.

Did anyone try to contact MG to let them know about the version difference? Is there a similar problem with any other chapter?

The workaround using watanagashi probably doesn't work well with tips, right?

**Comment by enumag** [comment]
Out of curiosity, where did you find the version numbers?

**Comment by P-Chang** [comment]
4.6.5f1 and 5.2.2f1 are not game version, it is Unity version.
It's mean both are nearly system but too different system, so patched one doesn't work.
Although, both vanilla DLL are not compatible in vanilla game.

DLL that you uploaded are really outdated one( don't have some code that newest one have)

Probably All files (without MS library and StreamingAssets) are completely different.

**Comment by ItaloKnox** [comment]
> Did anyone try to contact MG to let them know about the version difference? Is there a similar problem with any other chapter?

I contacted Doddler earlier today and he said the versions were identical, which is kinda true. It's one version behind, though both versions seem to support the same functions.

> Out of curiosity, where did you find the version numbers?

You can get them by seeing the .exe properties. Further confirmation can also be found in the output_log.

> 4.6.5f1 and 5.2.2f1 are not game version, it is Unity version.

**That makes so much sense.**
I guess there's nothing we can do, then.

**Comment by enumag** [comment]
What is the resolution here? If it is unfixable then we should add something about it to the wiki maybe?

**Comment by P-Chang** [comment]
MG store question bundle provided too much old build.

**Comment by ItaloKnox** [comment]
@enumag I ended up talking with Doddler and he updated the builds for us.
