### ISSUE TITLE
Reminder for Chinese update

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#14]
MG planed Engine update and implement of Chinese language support.
It may break MOD. and probably updating MOD in same day is impossible.

I can't know when it will come.

Steam user can downgrade with Steam Console

Press this link with your WEB browser
[steam://nav/console](url)

Console tab will available in your steam client.

Press Console tab and paste it in command box.

chapter1
`
download_depot 310360 310361 4410936638386498651
`
chapter2
`
download_depot 410890 410891 6649378427451771594
`
chapter3
`
download_depot 472870 472871 224693427286909718
`
chapter4
`
download_depot 526490 526491 3512022933343269940
`
chapter5
`
download_depot 577480 577481 1418629749600637923
`

Downloaded files are stored in 
`Steam\steamapps\content\$appid$\$buildid$`

**Comment by ItaloKnox** [comment]
I had no idea we could use the console in the client. I always had a copy of steamcmd for that.

Let's hope the update won't break anything. We'll probably have to merge the translation unless we want to get an influx of angry Chinese people.

**Comment by enumag** [comment]
With all the PS3 changes we have done I think merging the translation wont be possible.

**Comment by ItaloKnox** [comment]
Oh... you're right. We'll have to find a way of nulling it, then. That will probably be easier than merging, though.

**Comment by enumag** [comment]
If it is done the way @P-Chang thought on discord then nulling it is trivial for me. On the other hand merging translation would be next to impossible.

**Comment by P-Chang** [comment]
I do not think it is necessary to exclude the translation from EP6, but it would be impossible for us to merge the translation into the current MOD.

I think Chinese have own huge community, they can be merging own hand like Russian did.

**Comment by enumag** [comment]
I dont expect them to release EP6 with chinese right away. They need to catch up with 5 episodes of translation first and thats a lot, it will take them a while.

I think we should let the chinese use our patch as they wish and let them do the mod if they want. It would be outside of this group, but we could add a link to our readme.
