### ISSUE TITLE
Sprite Replace

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#15]
@enumag 
http://www.mediafire.com/file/d3hvgydvfqe9c8f/rulefile.csv

1st is PC name that we use now
2nd is PS3 name
3rd is expression

replacement
`ModDrawCharacterWithFiltering(1, 3, "%PCNAME%", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`
`ModDrawCharacterWithFiltering(1, 3, "%PS3NAME%", "%expression%", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`

`ModDrawCharacterWithFiltering(1, 3, "re_se_bi_a1", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`
`ModDrawCharacterWithFiltering(1, 3, "character/normal/re1a_bikkuriA1_", "2", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`

`ModDrawCharacterWithFiltering(1, 3, "night/re_se_bi_a1", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`
`ModDrawCharacterWithFiltering(1, 3, "character/night/re1a_bikkuriA1_", "2", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`

`ModDrawCharacterWithFiltering(1, 3, "re_se_bi_a1_zoom", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`
`ModDrawCharacterWithFiltering(1, 3, "character_zoomed/normal/re1a_bikkuriA1_", "2", "m1", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`

**Comment by enumag** [comment]
@P-Chang You made some mistake.

This has 18 arguments: 

```
ModDrawCharacterWithFiltering(1, 3, "character/re1a_bikkuriA1_", "2", "1" , "left", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 1300, TRUE );
```

But this has 19 arguments:

```
ModDrawCharacterWithFiltering(1, 3, "%PS3NAME%", "%EXPRESSION%", "2", "1" , "left", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 1300, TRUE );
```

Since the other two examples have 18 aruments I'm going to assume that the second one is wrong and should look like this:

```
ModDrawCharacterWithFiltering(1, 3, "%PS3NAME%", "%EXPRESSION%", "1" , "left", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 1300, TRUE );
```

----

Next, what about the backgrounds? Do you want to rename them as well somehow or keep them as they are?

**Comment by enumag** [comment]
Also what should the `%EXPRESSION%` be for things like these?

```
DrawBustshotWithFiltering( 6, "cinema", "x", 1, 0, 0, FALSE, 0, 0, 0, 0, 0, 25, 3000, TRUE );
DrawBustshot( 7, "Title02", 0, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 26, 3000, TRUE );
```

**Comment by P-Chang** [comment]
Sorry for mistake.　I'll edit it and repost.

Expression number is last number of sprite name like re1a_bikkuriA1_`1`(this)
I separate this for non lipsync mode. without this, non lipsync mode is really dreary.

I think background renaming is not necessary. 

In my plan. Leaving drawbustshot like using `cinema` and `Title02` and etc as it is.
ModDrawCharacter(WithFiltering) was designed for character only.

**Comment by enumag** [comment]
For onikakushi I found only one missing rule: `me_ta_fu_a2`.

For watanagashi there is one missing too: `me_ta_fu_a1`.

**Comment by enumag** [comment]
Oh so in the end the correct number of arguments is actually 17? Alright.

**Comment by P-Chang** [comment]
Yes, sorry for confusing.

basically, drawbustshot plus 2 arguments and drawbustshotwithfiltering plus 2 arguments.

**Comment by enumag** [comment]
Good. In that case I think I have the script ready for oni and wata except for the 2 missing rules mentioned above.

For tata I'll need to add some additional logic for weather sprites.

For hima I'm not sure how to handle child mion and rika.

**Comment by P-Chang** [comment]
Thanks.

Child Mion and Rika have only school uniform sprite, and these are used in only omake and, child sprites are not used in omake and normal sprites are not used in main chapter. So I think it's okay to process them separately.

I think ps3 name are used as zoom sprites in chapte3 and 4 is more problem.

**Comment by enumag** [comment]
> I think ps3 name are used as zoom sprites in chapte3 and 4 is more problem.

Actually I don't think that's a problem. There is only a handful of them so I can easily harscode them in and add the `character_zoomed/` prefix. Are there some more complications?

For weather sprites in tata it seems that sunset sprites have `_b` suffix and night sprite have `_a` suffix so it shouldn't be too difficult either.

The problem with child sprites is that for example `ri_si_de_a1` is used for both child rika (hima) and older rika (other chapters). Because of this I think we'll need a separate CSV for himatsubushi.

**Comment by P-Chang** [comment]
http://www.mediafire.com/file/ac9kc0adq9fwi6j/rulefile.csv
Included 2 missing sprite and fix mion sprite's position that I putted in lower.

If you think it is not problem, it is not problem. there are no complication except for chapter5

OK, I'll make it. separated one needs all or only child sprites?

**Comment by enumag** [comment]
Only child sprites. I can use the other CSV as fallback. But make sure there are no child sprites missing - I won't be able to detect them.

> there are no complication except for chapter5

What is the problem with chapter 5 and what can we do to solve it? I thought the sprites there already follow the PS3 naming so I thought it would be easier than the question arcs. Is that not the case?

**Comment by P-Chang** [comment]
I thought name in chapter 5 is same as ps3. But in vanilla these are bit different. In modded folder, there are question vanilla name and answer vanilla name and ps3 name.

**Comment by enumag** [comment]
One more problem with hima.

`oryou_Warai_0` is zoomed out
`Sunset/oryou_Warai_0` is zoomed in

Can you tell me what these two should be renamed to?

**Comment by P-Chang** [comment]
if it is only replacement, it is correct.

With argument separation
`"character/oryou_Warai_", "0",`
`"character_zoomed/sunset/oryou_Warai_", "0",`

**Comment by enumag** [comment]
Thanks. In that case I think I'm done with the hardcoded exceptions for tata and hima. Just waiting for CSV.

What can we do about the meakashi problems?

**Comment by P-Chang** [comment]
Anyway, I'll make meakashi vanilla csv after childs sprites.

For now, I suppose way is
1.Checking ps3 name and separate
2.Checking meakashi vanilla name and replace
3.Checking question name and replace

**Comment by enumag** [comment]
Note for myself: need to add some code to detect correct character numbers for child Mion and child Rika in Himatsubushi.

**Comment by P-Chang** [comment]
Finished child csv
http://www.mediafire.com/file/9ixuw5cuc706i1c/child.csv
http://www.mediafire.com/file/b7uak44nr4s8bqy/childzoom.csv

Just in case, separated zoomed one

**Comment by enumag** [comment]
@P-Chang Thanks, it loks good. I'm going to bed now but I'll update my script with these first thing in the morning and let you know how it goes. I don't expect any major problems.

**Comment by enumag** [comment]
@P-Chang Here is the result:

Tata:

```
No rule found for sprite "sa1a_WaraiA1_0".
No rule found for sprite "sa1a_AkuwaraiA1_0".
No rule found for sprite "iri2_Majime_0".
No rule found for sprite "sa5_MuhyouA1_0".
No rule found for sprite "sa5_MuhyouA2_0".
No rule found for sprite "sa5_MuhyouA1_0".
No rule found for sprite "sa5_AkireruA1_0".
No rule found for sprite "sa5_YareyareA2_0".
No rule found for sprite "sa5_YareyareA1_0".
No rule found for sprite "sa5_OdorokiA1_0".
No rule found for sprite "sa5_HannbesoA1_0".
```

Hima:

```
No rule found for sprite "oisi1_2_0".
No rule found for sprite "iri2_Def1_0".
No rule found for sprite "iri2_Majime2_0".
No rule found for sprite "iri2_Majime_0".
No rule found for sprite "miyuki_Hatena_0".
No rule found for sprite "miyuki_Kanashimi_0".
No rule found for sprite "miyuki_Huan_0".
No rule found for sprite "miyuki_Hatena_0".
No rule found for sprite "miyuki_Def_0".
No rule found for sprite "oisi2_8_0".
No rule found for sprite "miyuki_Neboke_0".
No rule found for sprite "miyuki_Hatena_0".
No rule found for sprite "miyuki_Kanashimi_0".
No rule found for sprite "miyuki_Huan_0".
No rule found for sprite "miyuki_Hatena_0".
No rule found for sprite "miyuki_Def_0".
No rule found for sprite "miyuki_Warai_1".
No rule found for sprite "miyuki_Def_0".
```

If you want I can add in some detection like if sprite ends with `_<number>` then cut off the number and use it as separate parameter.

Also character numbers for child mion and rika in hima should be ok now.

**Comment by P-Chang** [comment]
@enumag 
These are zoomed one, so make it `"character_zoomed/weather/SpriteNameWithoutLastNum" "LastNum"` is OK without Miyuki.

Miyuki should be `"character/weather/SpriteNameWithoutLastNum" "LastNum"`

Could I ask you to add it?

**Comment by enumag** [comment]
@P-Chang Sure. Just beware that if I add such logic it could cause some issues with meakashi - depending on how broken is the naming there.

**Comment by P-Chang** [comment]
Is it possible that making these process to hima only?
Meakashi use ****zoom for zoomed sprite. process that is needed in meakashi is Miyuki case.

**Comment by enumag** [comment]
@P-Chang Yeah I can enable it just for hima. But there were the same probles with tata. Maybe we should add them to the csv instead - there isn't too many of them.

**Comment by P-Chang** [comment]
OK,here
 http://www.mediafire.com/file/c44hvgd09ot8o7u/tatahimazoom.csv

**Comment by enumag** [comment]
@P-Chang Done. I don't quitew understand the problem with Miyuki though. How should I handle her sprites?

**Comment by P-Chang** [comment]
Fortunately, she have no change from ps3 name.

 `"miyuki_Def_0"` to `"miyuki_Def_", "0"` is fine.

Mekashi ps3 name sprites are same.

**Comment by enumag** [comment]
Ok. I just added Miyuki to the hima CSV as well.

**Comment by P-Chang** [comment]
@enumag 

I tested new patch. it could be compiled with some fix

You missed "character/normal".  "character/spritename" is not correct(some of reason is my mistake, sorry)
It will be fixed with using `character` as `character/normal`. but I think using `normal` looks directory smart for me. how do you think of it?


And, ModPlayVoiceLS needs TRUE in last.

**Comment by enumag** [comment]
@P-Chang Thanks for checking it. Is this alright then? https://github.com/07th-mod/onikakushi/commit/efd6e5b61b7fe6886412af53d3ea0d91042d83bc

**Comment by P-Chang** [comment]
Looks good, and compiler handle it completely and game works.
Thank you!

**Comment by P-Chang** [comment]
@enumag 
http://www.mediafire.com/file/t85qb0z5p25g8dr/mearule.csv
http://www.mediafire.com/file/jd0tqstyhbyw5zc/mearulezoom.csv

Meakashi list is finished.
Current files have lack of mouse variation, so I fixed with MG sprite mod.
So, it is bit different with QA list and AA(without Meakashi) list that I'll make in future.

Although, Mekashi list have too match duplicate name with QA list.
So you may need to make separated process with QA.

**Comment by Grelo** [comment]
If you are talking about BG's be careful  `-` `--` `_a` are not only weather variations and `+` is not only filter. If you delete them there will be a lot of missing files. There are images with the same name as PS3 version if i remember correctly but lot of them aren't. 
Meakashi needs to be done manually with great amount of care...

**Comment by P-Chang** [comment]
Don't worry. I just make Meakashi character list. And I checked `-` `--` `+` have only one weather variation.

Deleting is mean replacing like `me_si_him_a1_zoom--.png` to `me_si_him_a1_zoom.png`. 
And I also delete duplicate, So, you don't need worry about this.

**Comment by enumag** [comment]
@P-Chang I'll close this myself when I no longer need this issue. There are still some files I'll need later here...
