### ISSUE TITLE
New backgrounds/CGs for lipsync

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/higurashi-patch-compiler#18]
With the sprites pretty much sorted out, we still need to rename the backgrounds and CGs. We could just skip them, but the issue is that they are also affected by the same quality issues as the sprites.

Here are some comparisons: [Background](http://screenshotcomparison.com/comparison/124161) and [CG](http://screenshotcomparison.com/comparison/124162).

I still think we should also update those because the sharpening seems to be a little too strong. But if you guys decide to skip it, I'll accept it.

**Comment by enumag** [comment]
I'm not completely sure if we should rename them. But it will probably be difficult to replace them without renaming them first. @P-Chang What do you think we should do here?

**Comment by enumag** [comment]
And I'm still undecided whether the sharpening is good or bad for these. I'm a bit inclined to keep the sharpened ones to be honest.

**Comment by ItaloKnox** [comment]
Well, if you guys want to avoid the trouble we can just skip those and use them as is. I dislike sharpening but I can understand those who like it, it gives a more "anime" feel to the image.

If we skip them I'll have to find a way of taking only the backgrounds and CGs from our current packs, it'll take some time since I have to rely on the terminal.

**Comment by enumag** [comment]
@ItaloKnox If we end up doing that I'll write something to make it easy for you.

**Comment by enumag** [comment]
What I'm not quite sure about is why do I like sharpening on these but didn't like it on sprites? Maybe I just had too few examples to compare and I'd talk differently if I have seen more.

**Comment by EliEron** [comment]
Not sure if I get a vote here since I haven't done much for the project, but I personally dislike the sharpening. I actually felt this way back when the 1080p graphics were introduced as well, but I wasn't sure if I was the only one that had an issue with it.

Also since the sprites have been scaled to 1440p it would feel a bit strange leaving the CG and BG at 1080p, even though it technically works fine.

**Comment by ItaloKnox** [comment]
I think we'll scale back the sprites to 1080p as well. waifu2x really does improve the quality, but it's still an upscale. It stops being good at 1440p, but since the sprites only take a small portion of the screen, you don't get to see the 1440p imperfections.

**Comment by enumag** [comment]
The thing is that if we make non-sharpened patches now then it's easy to just sharpen them again later. It doesn't work the other way around though. So that's another argument to remove sharpening...

**Comment by enumag** [comment]
@ItaloKnox Oh so 1440p BGs and CGs are no good and we won't make them?

**Comment by ItaloKnox** [comment]
I agree about the pros of removing sharpening.

Now, about the 1440p thing, people running 1080p displays won't notice the imperfections but those running 1440p displays will. The issue with CGs or BGs is that waifu2x doesn't behave well with scenes with a lot of details. Since the sprites are pretty simple, it can scale them up quite a bit without looking upscaled, but everything else is another story.

**Comment by P-Chang** [comment]
I remember @irlPM said he can handle it with his scripts(I don't know how it works)

Although, we can combine question ark background and CGs with renaming only one sprites.

**Comment by irlPM** [comment]
Didn't I upload the bg/cg in 1080p for you @ItaloKnox ? I'll check the renaming process when I get home. I totattly agree that we need to replace the current bg/cg I don't like the shapening, and the colors are so much better. But well it is just my opinion.

**Comment by irlPM** [comment]
Here I found the link for the bg/cg in 1080p: https://mega.nz/#!Lg93hChT!KOp339ef3JypvHPHkKbvjOcKNJXpezHgqdTQ_tCZwpw

**Comment by ItaloKnox** [comment]
Yeah, you did. The link is actually already in our repo. Just need to replace them now.

**Comment by Grelo** [comment]
You can replace them if general audience like the normal ones more. I will just slightly sharpen them and use myself once you are done and release them as final. Still if we can make a thread on steam or r/visualnovels/ to know what people like and want it would only help, we can have normal ones as official and post a link to sharpened ones for those who want once im done. I would do that but im not good at this stuff.

**Comment by irlPM** [comment]
Or we could put a option in the installer? , I don't know. I'll try to put up a vote in discord.

**Comment by Grelo** [comment]
Is it ok for Sprites to be 2560x1440 or is 2560x1920 better?

**Comment by irlPM** [comment]
The currently ones are in 1440p.

**Comment by Grelo** [comment]
Yeah but we were making them 4:3 dunno why 16:9 now, that is why im asking.

**Comment by ItaloKnox** [comment]
@Grelo New sprites *have* to be 16:9 now.

**Comment by jwgrlrrajn** [comment]
@Grelo, what settings did you use for sharpening? I'm wondering if it might make my MG Zoom sprites look slightly better.

**Comment by Grelo** [comment]
@jwgrlrrajn They would need different amounts than PS3 sprites.

**Comment by Grelo** [comment]
Tommorow ill put here a link for 1440p sharpened BG and CG-only graphic pack. In case you decide to use a switch or option for it in the installer.

**Comment by jwgrlrrajn** [comment]
Alright, I played around with the settings, and I came up with this. Have a look and tell me what you think. If enough people prefer the sharpened version, I can go ahead and update all the MG zoom sprites. http://screenshotcomparison.com/comparison/127848

**Comment by Grelo** [comment]
So here it is BG's and CG's for those who like it spicy.

https://mega.nz/#!ZVkW3A7T!-sB16Dc-BAhLfW3qHbNFd_xtPOfcI8yMtNdxnNW4ORE

**Comment by enumag** [comment]
According to the vote @irlPM started on Discord we should use the non-sharpened sprites. In my opinion we should do that without any other effects. If we have a non-sharpened patch we can easily apply some smaller sharpening later or make whatever alternative versions we want.

@Grelo @P-Chang @jwgrlrrajn @ItaloKnox @irlPM Are you all in favor?

----

The main problem now is the BGs and CGs. As far as I know the numbers in our current patches are pretty much random so we can't just match them automatically to the PS3 names, right?

So we'll need some CSV files similar to what P-Chang made for sprites. With that I'll be able to make a program to both rename everything in the scripts and to separate the images needed for each chapter from the rest.

**Comment by ItaloKnox** [comment]
> we should use the non-sharpened images. In my opinion we should do that without any other effects. If we have a non-sharpened patch we can easily apply some smaller sharpening later or make whatever alternative versions we want.

100% in favor. I still believe having the untouched PS3 graphics would be better, touched graphics or scripts that deviate from our vision of the project (that is to port everything from the console while keeping it uncensored) should be interesting for forks, but not for the official thing.

About the issue of the remaining graphics, I have no idea on how to fix it in a way that doesn't take a lot of time. I thought about running a dupe comparison and it might actually work, but we'll need to write down a CSV with original and new filenames. It'll be very time consuming but I can't think of a better solution. If you guys have no other ideas on how to make this easier, we can proceed with this.

**Comment by jwgrlrrajn** [comment]
I'm in favor of the unsharpened PS3 sprites, even though I don't really use them. I'll be okay with whatever we decide to do with the BG's/CG's, as long as they don't look too blurry. Worst case scenario, I can always sharpen my own images, if needed.

**Comment by enumag** [comment]
@jwgrlrrajn I'm guessing that you, Grelo or Iri will make some sharpened alternative patch. I'll probably use it as well when playing.

@ItaloKnox I don't think there is any other way. I considered matching them by a script but the different sharpening of the images makes that pretty much impossible.

**Comment by P-Chang** [comment]
I'm fine if everyone are fine.

**Comment by Grelo** [comment]
So no poll? Ok. Upon checking the new unsharpened sprites i agree they don't need the sharpening, pretty good. As of BG's and CG's i think use what you like as we don't know what general public prefer i would say normal ones and  i will use mine so no problem ;)

**Comment by ItaloKnox** [comment]
We actually did a poll in our Discord channel, as far as I know, the majority was ok with unsharpening it. I'm not really against using sharpened backgrounds and CGs (even though my monitor dislikes them), but there's not really a way around it since the new assets still need to be renamed before even considering sharpening it again. 😩

**Comment by Grelo** [comment]
Plus don't forget the chapters have additional BG's that doesn't exist in PS3 folder. Or @P-Chang is ready to make it like in PS3 with different kind of filters, auto zooming PS3 BG's etc..?

**Comment by P-Chang** [comment]
I didn't.
BG replace don't have higher priority for me. because lipsync work without it.

I'm busy in making DLL and character sprites name comparison.

**Comment by irlPM** [comment]
Hm  anyone find other solution? I think I'll need to rename them manually...

**Comment by enumag** [comment]
No. I don't think there is any other solution.

**Comment by enumag** [comment]
Doing all the manual work needed here might be too much for one person. Maybe we should split them and do do one chapter each? I mean I can certainly manage one chapter, but taking all of them feels like too much work.

Basically for each chapter we need a text file with `<bg file in current patch>` => `<same bg file in PS3 resources>`.

If anyone wants to help, please comment which chapter you're taking before you begin to avoid overlap.

**Comment by ItaloKnox** [comment]
I should be able to work on one chapter over the next week. Don't wanna say Onikakushi because there's a chance I might stall progress if anything goes wrong. Ideally, I would like to do Himatsubushi.

**Comment by enumag** [comment]
Kay @ItaloKnox, Hima is yours.

I'm taking Tatarigoroshi.

**Comment by P-Chang** [comment]
you guys says that BG or CG?

BG are same without one file (I checked it few month ago, but i lost which is it)

**Comment by enumag** [comment]
@P-Chang You man CG, right? At least that's what @DoctorDiablo said on Discord...

**Comment by enumag** [comment]
I mean CGs were taken from PS3 files in the first place so it makes sense. BGs on the other hand were manually replaced from the ugly MG originals - renaming them in the process.

**Comment by P-Chang** [comment]
I mean QA Backgrounds like school, village, police.

**Comment by enumag** [comment]
Judging from how the patch was made I believe there will be quite a few differences. Well we'll see I guess. It can only make our work easier so it's fine.

**Comment by P-Chang** [comment]
I checked simple diff, oni, wata, tata, background are same.

In Hima
```
bg_027
bg_046
bg_046_a
bg_048
bg_050_a
bg_093a
bg_208
bg_223
```
are different. sorry differences is not one.

**Comment by enumag** [comment]
@P-Chang I really don't understand what you mean. I'm currently comparing Tata. For example this image:

![bg_010](https://user-images.githubusercontent.com/539462/34890905-f705337a-f7d3-11e7-97f9-6abc7b9d2ce9.png)

is named `bg_010.png`. In the [PS3 resources](https://github.com/07th-mod/resources/releases/download/Nipah/HigurashiPS3-Graphics01.zip) the name is completely different - `jd4.png`. This goes for all backgrounds. There are no `bg_*` images in the PS3 files.

**Comment by P-Chang** [comment]
@enumag 
I mean modded Oni and Wata are using same image.

In Tata bg_108 is different with Oni and Wata.

In Hima
``` 
bg_027
bg_046
bg_046_a
bg_048
bg_050_a
bg_093a
bg_208
bg_223
```

are different with other arks.

we don't need comparing over 100 BG files 4 times.

**Comment by enumag** [comment]
@P-Chang Yeah I understand now. Are you certain that `bg_108` is the only different one or should we double check?

Mea uses completely different names so that will need to be done separately.

**Comment by P-Chang** [comment]
Yes, combine Oni Wata Tata and double check bg_108 make it easy, I think.

**Comment by irlPM** [comment]
Watanagashi BG/CG new graphic. https://mega.nz/#!Tt9RkIoL!8zNqUY94lA8pXyUt7__zwZOrC2-DV3IyQy7sl6O_giY

**Comment by enumag** [comment]
@irlPM I checked the txt file but it seems there are quite a few missing - `bg_004`, `bg_005`, `bg_011`.... many more. Also the filder with the actual images is not really necessary. I'll write a script to compile the patch anyway.

**Comment by irlPM** [comment]
All the others are in Oni. The bg are the same so it doesn't make sense to rename it two times.

**Comment by enumag** [comment]
@irlPM Ah, ok. We don't have a file for Oni yet though - or did I miss it?

**Comment by irlPM** [comment]
Yes, I don't think we have one.

**Comment by enumag** [comment]
Here is a complete list for Tatarigoroshi: https://www.dropbox.com/s/q4g1yjy466gpoga/tata.txt?dl=0

Since it's complete it contains files that are in Oni and Wata as well so this might make Oni list a bit easier to create.

Also I'm probably blind but I just couldn't find this image anywhere among the PS3 backgrounds. Can someone look for it?

![bg_235](https://user-images.githubusercontent.com/539462/34921464-e19dc884-f982-11e7-90b3-357a5c38aede.png)

**Comment by enumag** [comment]
Oh. That makes sense. But where is the original (before sharpening and waifu2x)?

**Comment by enumag** [comment]
I also couldn't find these three:

![toketu1a](https://user-images.githubusercontent.com/539462/34921722-49b9c546-f986-11e7-8b13-290b3410f6e8.png)
![toketu1b](https://user-images.githubusercontent.com/539462/34921723-49d26268-f986-11e7-97f0-8abd363d2424.png)
![toketu1c](https://user-images.githubusercontent.com/539462/34921724-49e960f8-f986-11e7-948d-6fa7608c547e.png)

**Comment by P-Chang** [comment]
I think @Grelo took it from umi backgrounds.

**Comment by ItaloKnox** [comment]
I'm about to get started on Hima. Just to be sure: we're just looking for the backgrounds, right? Should I also list stuff like ``black``, ``hima001``, ``2``, ``ex_otsu_hima``? These are reusable stuff so I'm unsure if we're listing them.

**Comment by enumag** [comment]
Just bgs. But also add bgs that don't start with bg_. In tata it was these:

```
aka1
aka2
bg0
fire
furiker_a
furiker_b
haikei
ryuuketu1
```

**Comment by ItaloKnox** [comment]
Gotcha. Also, how do you add the names of weather BGs that have the same filename in our patch?

**Comment by enumag** [comment]
Ideal is `night/bg_xxx,ps3name`

**Comment by ItaloKnox** [comment]
[himatsubushi.txt](https://github.com/07th-mod/higurashi-patch-compiler/files/1632504/himatsubushi.txt)

There you go. I used [an old friend of mine](http://www.freeware-guide.com/rareware/DupDetector.html) and it showed to be quite reliable for this task. You could parse the log and automate the process, but I wouldn't really do that since there are a few backgrounds with too many similarities. Though you could try to fine-tune the app to find only direct matches.

**Comment by Grelo** [comment]
@enumag I'm not sure but i only worked with PS3 and older chapter's images. And with me working side by side with Vita(PS3) version it should be almost 1:1.

**Comment by enumag** [comment]
@Grelo So even you're not sure where the bathroom and 3 blood images came from? I guess we'll just have to keep them from the current patch then.

**Comment by Kamlingen** [comment]
All of the are from Umineko and probably leftover from TheGuraGuraMan patch.

**Comment by enumag** [comment]
@ItaloKnox Sorry for not answering you sooner. Thanks for the hima CSV, it looks good. Can I ask you to make Onikakushi as well? Using the Dup Detector you're much faster at this than I'm. You almost make it sound easy.

@Kamlingen Thanks, that explains things.

Can someone get me the originals for the 4 files from umineko? (I mean non-sharpened, non-waifu2xed versions.)

**Comment by ItaloKnox** [comment]
Sure, leave it to me. I'll start working on it tomorrow.

The files for Umineko should be there: http://www.seacats.net/image/res/729.html

I also have an extracting tool repo on my profile if you want to directly extract it from the game itself. If you ask on Discord someone can share their copy.

**Comment by ItaloKnox** [comment]
[onikakushi.txt](https://github.com/07th-mod/higurashi-patch-compiler/files/1633260/onikakushi.txt)

Just had some idle time so I did the list as promised. The program is really reliable, it's also capable of comparing original PC backgrounds to PS3 backgrounds, lol. Takes a lot of fine-tuning, though.

If possible, double check for me the last few lines. I'm afraid I'm also picking some system images, so it's going to be bad if you don't plan to rename the PS3 images to the same names we're currently using (instead of renaming current to PS3 patterns).

**Comment by enumag** [comment]
> it's going to be bad if you don't plan to rename the PS3 images to the same names we're currently using (instead of renaming current to PS3 patterns).

The goal here is to use the PS3 names. Ok I'll check it. Thank you!

**Comment by ItaloKnox** [comment]
Can't we just rename the CG/BG PS3 filenames to our current filenames? That would cut down all the work in the scripts and normally we wouldn't miss anything. I kinda feel like we're trying to achieve the same thing but in a harder way. At least for chapters 1~5, we could try new filenames in ch.6 onwards, since those have to be made from scratch.

**Comment by enumag** [comment]
All the work in the scripts will be done by my script which is already written so that's irrelevant. At this point we're pretty much ready to use the PS3 names. I don't see much of a reason to not do this change at this point but if you do have some reasons please tell me.

**Comment by ItaloKnox** [comment]
Oh, then that's okay. Just make sure to get the system images from our current patch, but you must have already thought about that. I'll be waiting for my turn, then. 😄

**Comment by enumag** [comment]
Sure I did, 🙂 Based on the CSV files we have now I can pull all sprites form PS3 (normal) Iri's packs (weather variants) and all bgs and cgs from PS3. All other images will remain unchanged.

**Comment by P-Chang** [comment]
@enumag 
I saw BG and CG replacer in repo. wouldn't it better that using `CG/cutscene` or `CG/scene` or something intsted of `CG/cg`.

**Comment by enumag** [comment]
@P-Chang I have a list of things I need to ask you guys before continuing further. This is actually one of them. I'll write them all to a new issue this evening (which might be tomorrow you, depending on timezones).
