### ISSUE TITLE
[WIP] New Graphics patches compilation

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#21]
This is just notes for myself. Please ignore this issue. I'll ask when I need help.

- Add Graphics01 to downloads, no need for others. Should go to ps3/ dir.
- Get final decision about 1080p vs 1440p for sprites and bgs (separately).
- Add missing sprites to downloads.
- Double check things like "eye".
- Note about errors maybe not false positives.
- ~~Waifu2x some directories.~~ Use 1440p resources.
- New steam weather sprites.
- Need to get files for the Onikakushi poem.
- Textboxes are separate download currently.

**Comment by P-Chang** [comment]
Chapter1:
http://www.mediafire.com/file/zoylo9o7oc81q81/chapter1dlls_v4.x.x.rar
Chapter2:
http://www.mediafire.com/file/2ljfb9xpzw64d7j/chapter2dlls_v3.x.x.rar
