### ISSUE TITLE
New Graphics patches questions

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#23]
We're making good progress on all the issues on our roadmap (#19) so I'd like to have a testing version for Onikakushi out in two weeks or so (let me know if you think it's overly optimistic estimate). Before we do that I need answers to some questions.

1. The CSVs and scripts for Graphics patches are pretty much done for Onikakushi (some work is still needed for other chapters). I need a final decision about whether we use 1080p or 1440p sprites and 1080p or 1440p CGs and BGs. If I remember correctly the consensus was something like "1080p sprites to avoid stuttering" and "1080p CGs and BGs because Waifu2x is not very good for higher resolutions" - can someone confirm or clarify this for me? (@ItaloKnox?)

2. If we go with 1080p sprites then I need 1080p weather variants for them. In our resources repo I only see 1440p weather variants. Do we have 1080p ones somewhere? (@irlPM, @ItaloKnox?)

3. I'd like your feedback on the directory structure for the new graphics patches. Here is what I'm currently planning: (@ItaloKnox, @P-Chang, everyone else)

```
CG/
    character/
        normal/
        night/
        sunset/
    character_zoomed/
        normal/
        night/
        sunset/
    backgrounds/
    scenes/ (contains CGs)
    <other images, typically leftovers form current patches>
CGAlt/
    character/
        normal/
        night/
        sunset/
    character_zoomed/
        normal/
        night/
        sunset/
```

**Comment by ItaloKnox** [comment]
Yeah, I'm also a little confused about the current state of the graphics. If @P-Chang says the game can handle 1440p graphics without any issues, then let's go with that. The assets are done already, so it should take a lot less time to compile.

Now about weather variants, we don't have 1080p sprites. Everything (including normal sprites) are in 1440p.

The structure looks good, I like it. Having it more organized is a plus if we need to change anything in the future.

**Comment by P-Chang** [comment]
it looks good directory structure.

Anyway, would we make QA backgrounds to universal package?
like `character` and `scenes` to Ark separated one package, and universal background package. 

Although, I think we should decide how to treat folder like `a` `s` `t` etc in a few days.

---
1440p have no big problem on my rig, but I don't know why I still feel anxiety.
But I have no objection for using 1440p on pre-release.


Something is bugging me is some of assets(from upscaled vanilla or made by someone or myself) are still 1080p, and 1080p is already too much high resolution for basic settings.
These still no problem on my rig, but it is really gloomy for me.

**Comment by irlPM** [comment]
I can do the 1080p sprites if you need them. But I won't be home until 23/01, travelling and stuff.

**Comment by irlPM** [comment]
For the folder organization, I think they're ok.

**Comment by enumag** [comment]
I didn't really understand what @P-Chang wrote above so I checked with him on Discord to clarify. Here is the conclusion:

- Universal package was not a good suggestion.
- Files from PS3 `a`, `s` and `t` directories might be needed later but no need to worry about them now.
- 1440p might have some problems but it will be good to get some real feedback so we'll use it for the pre-release.
- His concern about assets resolution can be disregarded for now.

----

@irlPM This means we won't need 1080p sprites as soon as I initially thought. We'll probably need them for final release but no need to worry about it until February.

**Comment by enumag** [comment]
@ItaloKnox By universal package he meant there would be one zip with backgrounds for chapters 1-4. But he checked the numbers and the chapters have way too many different backgrounds so the disk overhead would be too big.

**Comment by ItaloKnox** [comment]
Yeah, that's not really a good idea. I think we should stick to our usual format since most people are already used to that by now (and I don't want to rewrite the documentation).

**Comment by P-Chang** [comment]
almost of them were really foolish suggestion, sorry.

**Comment by ItaloKnox** [comment]
Don't worry about that, it might be useful for something else (like that symlink project you made). For the regular users, I would avoid that.

**Comment by DoctorDiablo** [comment]
The structure looks good, but I think it might help to use slightly shorter directory names.  It's just that the default installation directory for the steam version on Windows is already really long, and we're going to make it even longer.  We'll end up with full paths like:
> C:\Program Files (x86)\Steam\steamapps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CGAlt\character_zoomed\sunset\re2a_hig_muhyouA1_0.png

How about: 
>sprite/
>zoom/
>bg/
>scenes/

**Comment by enumag** [comment]
I'm not a fan of too short names like bg but we could go with something in between like this:

```
sprite/
portrait/
background/
scene/
```
