### ISSUE TITLE
Eye CG

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#26]
![eye](https://user-images.githubusercontent.com/29869319/35463954-ae0a1140-0336-11e8-8fbf-9f4fc2ddf1c9.png)
![cg_eye](https://user-images.githubusercontent.com/29869319/35463974-c9f16c64-0336-11e8-800b-bdd62c445b76.png)

Personally I prefer PS3 gross eye, but @enumag dislike it.
Isn't putting PS3 one to `CG ` and MG one to `CGAlt` better?

Honestly I want not to watch this in directory, but I feel no fear in game from MG one.
Although, this one used in some non Sonozaki scene too, so MG one is bit strange.

I can replace it easily in my own use, so rejection is fine for me.
But some of user that want to more fear was disappointed, I think.

**Comment by enumag** [comment]
Personally the PS3 version (the top image) feels just too different from other CGs and images in the game. It's so out of place that I just hate it.

Of course I can easily replace it just for myself. We just need to decide which should be default.

**Comment by ItaloKnox** [comment]
I like the scary eyes, Ryuukishi uses it in key moments and perfected the use on Umineko. If I recall correctly the point is really to feel out of place and make you feel uncomfortable. At least for me, I would do what @P-Chang said and use that on ``CG`` and leave the other on ``CGAlt``. 🤔

**Comment by irlPM** [comment]
I remember playing the game and when the ps3 eyes showed up, I was scared as shit. So I would say that I prefer the scary eyes, MG just looks meh don't really know how to describe it.

**Comment by Grelo** [comment]
Top eyes in other words PS3.

**Comment by enumag** [comment]
Ok we'll go with PS3 eyes then. Thank you all for the feedback. 👍
