### ISSUE TITLE
replacer problem

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#28]
https://github.com/07th-mod/onikakushi/commit/c1a86fa99646b0c9c012e41bb0eae458afcf8ad9#diff-37e0fa13a07de61fb76eaaad24871a36L3888
I don't know first argument of layer number was deleted. it seems happen in only here.

https://github.com/07th-mod/onikakushi/commit/52e935748d9b8c827e5dd3c7a90212c5949fee49#diff-cb2887916ddfd1b17b02070d8efff959R3276
Drawbustshot changed in ModDrawCharacter

**Comment by enumag** [comment]
Fixed, thanks.
