### ISSUE TITLE
Apologies

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#30]
Since I looked discussion for new disclaimer image, I lost motivation.
Image give me regret.

I realize I have no rights for using assets, I'll get out here.

Sorry for your times that was used for my ideas, especially enumag.
I learned many and it is really interested times, my apologies.

**Comment by InochiPM** [comment]
@P-Chang I feel as though it’s my fault for those feelings you have and I’m sorry. Sometimes we all lose motivation to do things and such, a lot of your ideas are and we’re awesome and a lot of the cool shit that’s been going on with this patch has been with your help! Some of us don’t know how to do the amazing things you have figured out to do to make this project that much better and we couldn’t have done it without you and all of the others that are helping on this project! So there’s no need to apologize or leave the project, just give it some time and you’ll find the motivation once again like we all do.

**Comment by InochiPM** [comment]
Since I did just kinda fly in here and start pitching ideas about stuff, I’m sorry! I just hate to see someone so awesome leave a project like this partly because of me.

**Comment by ItaloKnox** [comment]
Honestly, I don't think it was your fault or you meant anything bad, @InochiPM. Maybe there's something we haven't been told about, and I respect that.

I appreciate the time you spent working with us and helping to make the game better, @P-Chang. I am not sure what caused you to rethink and give up on it, but don't feel bad about your choice. We will definitely miss you, but it could happen to any of us. If someday you decide to come back and help us again, we will still be at the same place waiting for you.

In case you want to talk, you can catch @enumag or me on Discord privately. We will be there if you need us.

**Comment by Grelo** [comment]
@P-Chang You did a huge amount of work and implemented things which were hard to implement or 07th Modding was struggling with and because of that every fun of Higurashi series can now enjoy these additions and experience this great story in even better form. Thanks.

The members here will miss you but there will always be hope inside that one day you will return with enough motivation to aim even higher and make even better version of this mod.
The doors will be open.

**Comment by irlPM** [comment]
We're doing nothing wrong. You, me and all 07th mod team are trying to make everyone  experience Higurashi and others Ryukishi works in the best form possible, maybe we don't have the legal right to do this but when I was reading higurashi this patch right here bring up the experience to other level. So if you are felling guilty or regret about your work here, you really shouldn't, What you did in this team affected thousands of people in a positive way, they were able to read Higurashi with everything that has to offer. So please, don't regret it.
Everyone will miss you, thanks for all your work. I respect your decision but If you can please rethink it after a while.. Thanks for everything @P-Chang

**Comment by enumag** [comment]
The others have said everything that was on my mind. We might not have the "rights" to do these things legally but for many people (myself included) the game is completely unplayable without our patch. So this is definitely a good thing.

Thanks for everything you did for this project @P-Chang. We'll miss you. In case you change your mind the door is open.

----

For anyone wondering what kind of effect this will have on our patches, I'll post a new issue about that soon. It is a serious blow but we'll do our best to continue.
