### ISSUE TITLE
Resource gathering

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#32]
Currently we're preparing to write down the documentation of how we make our patches. I'll make another issue about that when it's ready.

For now I'd like to put together all the resources we're using to add the features. We have most of them in the resources repo of course but there are some missing parts. Here I'll try to write down what we have and what we need you to upload for us. Can you guys upload the missing stuff or post a link if you uploaded them previously?

Voices from PS2 and PS3 versions
----

- [x] PS2 voice files (https://github.com/07th-mod/resources/releases/tag/Nipah)
- [x] PS3 voice files (https://github.com/07th-mod/resources/releases/tag/Nipah)
- [x] Voice insertion script (https://github.com/07th-mod/voice-inserter)

Backgrounds, sprites and CGs from PS3
----

- [x] PS3 originals (https://github.com/07th-mod/resources/releases/tag/Nipah)
- [x] PS3 upscales (https://github.com/07th-mod/resources/releases/tag/Hanyuu)
- [x] Weather sprites (https://github.com/07th-mod/resources/releases/tag/Hanyuu)
- [x] Photoshop filters to make the weather sprites (https://github.com/07th-mod/higurashi-patch-compiler/files/1734208/Iluminacao.zip)

Updated MG sprites
----

- [x] Source files (PSD?) for the edited sprites (https://github.com/07th-mod/higurashi-patch-compiler/files/1734397/TheDoctor.s.Higurashi.Base.Edits.zip)
- [x] Photoshop filters to make the weather sprites (https://github.com/07th-mod/higurashi-patch-compiler/files/1734398/TheDoctor.s.Higurashi.Photoshop.Actions.zip)

@jwgrlrrajn I'm not entirely sure which sprites you changed but I remember changes to Ooishi, Chie, child Mion, child Rika and towel Satoko. And I think there was some talk about Shion, not sure if that's done. Anything else?

ADV-mode
----

- [x] Script updater (https://github.com/07th-mod/higurashi-patch-compiler)
- [x] PSD for the windo_filter image (https://mega.nz/#!0dU2lQSY!Z3hcE2gHEthGuG22uI2bskBAYj6uCilmvnW_IFK_jIQ)

DLL updates
----

- [x] Current DLLs (packed in the individual releases)
- [x] DLL hacking tool (https://github.com/0xd4d/dnSpy)
- [x] Decompiler (https://www.telerik.com/products/decompiler.aspx)
- [x] Souce code (https://github.com/07th-mod/higurashi-dlls)
- [x] Script updater (https://github.com/07th-mod/higurashi-patch-compiler)

LipSync
----

- [x] PS2 and PS3 voice analysis files (cc @ItaloKnox)
- [x] Script updater (https://github.com/07th-mod/higurashi-patch-compiler)

@ItaloKnox I can't see them in the resources repo. Did I miss them?

PS3 Poems
----

- [x] Original japanese text (https://github.com/07th-mod/higurashi-patch-compiler/files/1731026/hannyu_poem_ps3.txt)

New UI
----

- [x] Editor to extract and replace the assets (https://github.com/07th-mod/higurashi-patch-compiler/files/1734562/Unity_Asset-Editor.zip)
- [x] Latest version of the UI with source images (https://github.com/07th-mod/higurashi-patch-compiler/files/1734563/Higu_ONI-UI.zip + https://github.com/07th-mod/higurashi-patch-compiler/files/1734572/Higu_UI-PSD.zip)

Misc
----

- [x] Fonts, logos, anything else? (https://github.com/07th-mod/higurashi-patch-compiler/files/1734571/Higu_Logo.zip + https://github.com/07th-mod/higurashi-patch-compiler/files/1734573/Higurashi_Fonts.zip)

I know that some of these things were uploaded before but I've some problems with finding them plus you guys might have some newer versions.

Thanks for all of your contributions. Let me know if I missed anything.

**Comment by ItaloKnox** [comment]
Here is the file with all the poems: [hannyu_poem_ps3.txt](https://github.com/07th-mod/higurashi-patch-compiler/files/1731026/hannyu_poem_ps3.txt)

It also contains the previous (unfinished) translations. A simple edit would take care of it.

**Comment by irlPM** [comment]
Here is the weather filters, it is a photoshop action file.
[Uploading Iluminacao.zip…]()

**Comment by enumag** [comment]
@irlPM The link is not working...

**Comment by irlPM** [comment]
Fixed @enumag

**Comment by jwgrlrrajn** [comment]
Here's my PSD's and ATN's. No Shion edits were discussed, though there was a WIP Airsoft Holster and Pistol I was trying to make for Mion. I couldn't get past the leather strap, but I went ahead and included it.

[TheDoctor's Higurashi Base Edits.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1734397/TheDoctor.s.Higurashi.Base.Edits.zip)
[TheDoctor's Higurashi Photoshop Actions.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1734398/TheDoctor.s.Higurashi.Photoshop.Actions.zip)

**Comment by enumag** [comment]
@jwgrlrrajn Thanks. Can you drop the zoom bases on Mega? Also were they created by waifu2x or by some other means?

**Comment by InochiPM** [comment]
@enumag Here are the two zip files of the Asset Editor, as well as the UI zip i had put together. 
I'll upload the PSD files for the Logos,the fonts and the UI PSD's soon

Note: to use the Asset Editor you have to use 64x
[Unity_Asset-Editor.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1734562/Unity_Asset-Editor.zip)
[Higu_ONI-UI.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1734563/Higu_ONI-UI.zip)

**Comment by enumag** [comment]
@InochiPM Thank you! :-)

@Grelo I found this PSD for the screen filter but I'm not sure if its the latest version and if it contains the Kai version as well.

https://mega.nz/#!0dU2lQSY!Z3hcE2gHEthGuG22uI2bskBAYj6uCilmvnW_IFK_jIQ

**Comment by jwgrlrrajn** [comment]
@enumag, they were created using Waifu2x, then they had a mild sharpening filter applied to them to help tone down the blurriness.

**Comment by jwgrlrrajn** [comment]
Here's the zoom bases and PSD's of all characters up to Tatarigoroshi that I've zoomed in on so far. You'll want to align the sprite you're zooming with the the base sprite layer, turn off all layers except the one you're saving, then save and Waifu2x to the size specified in the folder. Align the zoomed sprite with the zoomed in base, and turn off all layers expect the one you're saving. After it's saved as a seperate png, open it and use the Higu Sharpen action, then save again. Do NOT sharpen the image in the PSD, since having the raw files makes it easier to make adjustments later on.

https://mega.nz/#!6EgHTRwI!Ll8OF50NzvrICM8Y1OYBf3u61-cCEfQTXylAVssUGf0

**Comment by InochiPM** [comment]
@enumag So here is an updated version of the Higu-ONI ui file, 
[Higu_ONI.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1735459/Higu_ONI.zip)

Here is the .asset file, for the most part i figured out the issues with the textures but the only one i couldn't get to work is the areyousure_dialogue it wont turn transparent no matter how i edit the settings lol 
[sharedassets0.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1735461/sharedassets0.zip)

**Comment by InochiPM** [comment]
@enumag Just as an update, I got the windows version of the New UI patch to work finally after some editing. 
I also found out that the Mac/Linux version of the asset files are much smaller and have a different id number placement so i had to go in and re-do the ui patch with the mac files. 
Depending on what system your running they have to download the correct file, and remove the _WIN or _MAC from the file name and replace the asset file. 
[Windows ONLY asset file](https://app.box.com/s/dnf84d69hazfdzwzu0siygnirwk4lgh5)
[Mac & Linux ONLY asset files](https://app.box.com/s/jot0snglmrxxcz7q9zlgaeycbr3rebjv)

**Comment by ItaloKnox** [comment]
[Onikakushi-Assembly-LipSyncDefault.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1736086/Onikakushi-Assembly-LipSyncDefault.zip)
[Tatarigoroshi-Assembly-CSharp-LipsyncDefault.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1736087/Tatarigoroshi-Assembly-CSharp-LipsyncDefault.zip)
[Watanagashi-Assembly-LipSyncDefault.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1736088/Watanagashi-Assembly-LipSyncDefault.zip)

Just dumping @EliEron dlls here so I don't forget about them later. I'm also updating the Hanyuu tag with the analysis files in a few minutes.

**Comment by enumag** [comment]
@InochiPM Thank you! How did you solve the transparency problem? Such issues are precisely what we need to write down for the documentation.

**Comment by InochiPM** [comment]
@enumag I litterally have no clue how i fixed it to be honest, i changed the settings of that file many different times. But if i had to guess it was because i changed the mode before importing the file instead of changing it after. So Note to self change the mode first then import the file

**Comment by Grelo** [comment]
@enumag Yep. It is the latest. Kai is there in layers too.

**Comment by enumag** [comment]
Ok, that's everything then. Thanks all of you!

@ItaloKnox When you have time please organize all these in our resources repo (if you didn't already) and close this issue.

**Comment by ItaloKnox** [comment]
Done. Everything is under ``Higurashi-MixedFiles.zip`` on Nipah. I intentionally left out files that are already uploaded in separate archives.

**Comment by enumag** [comment]
@ItaloKnox Awesome. Thank you!
