### ISSUE TITLE
ADV Textbox Swapping

### ISSUE THREAD

**Issue by InochiPM** [07th-mod/higurashi-patch-compiler#35]
So i talked about this on the discord chat, because i was playing around with the idea of a text box like the one in Sui, Matsuri and now Hou with its upcoming release onto the Switch. 

Since we had a basic catch all for the first textbox that took up the entire bottom half of the screen, making some of the scenes with just black background kinda loose their feel for how scary some of the scenes are supposed to be, and i know it doesn't matter because most of the user/player base turn off the onscreen menu anyway making the use of a text box like the ones used in the PS3/PS2/Switch games much more appealing.

So i thought we should try and see if there is a way to have the script or the engine recognize when there is either narration or character dialogue on screen and change the text box accordingly. 

Also we should see if there is also a way to swap the text boxes to Japanese logo's like how the engine has the two names set for Japanese, if the Japanese option is set it would/should change the logo in the bottom corner of the box itself. 

Since we cant really make a replica of the PS3 box style in question, because the engine used a method that stretched the name tag accordingly for the name of the person in question. 
Short name = Short name tag, 
Long name = Longer name tag, ect..

So the name tag on the voiced dialogue would have to be at a set size for the character names, as of now the longest name that fits correctly is "Keiichi's Mom" 

I'll paste below the text boxes I made to test out in the engine, so far they look nice, simple like the ones from the console games.
![test_1_adv](https://user-images.githubusercontent.com/13459080/37754324-79afd02c-2d77-11e8-9985-321d9701fe55.png)
![test_2_adv](https://user-images.githubusercontent.com/13459080/37754325-79c2a8b4-2d77-11e8-9beb-d31db9bf5e16.png)

**Comment by Grelo** [comment]
I made these, dunno around a year ago but the team didnt like the round corners and the separated space for a name i think so we used what we are using now. Maybe that changed.

**Comment by thinh192** [comment]
Higurashi dialog box Hey try
![Uploading Không Có Tiêu Đề51.jpg…]()

**Comment by ItaloKnox** [comment]
Not sure why this issue is still open, but I think that at this point in development, anything about the textbox should be in a new issue.
