### ISSUE TITLE
Himatsubushi & Meakashi patches

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#37]
Graphics packs
----

I believe we already have everything for Himatsubushi.

For Meakashi we should:
- Remake [tips and text images](https://www.dropbox.com/s/4x9k2aa640ujvxc/text.7z?dl=0) (just those you want to remake). (@InochiPM)
- Remake the [customized CGs](https://www.dropbox.com/s/2wbgj51x6s8lir3/bg.7z?dl=0) (choose which you want to remake, we'll just keep the rest). (@irlPM)
- Fix missing sprites (I'm checking what's wrong now, will comment about it later today).
- Remake CGAlt sprited pack (I'll send it to TheDoctor when missing sprites are fixed).

@IrlPM Upload the Photoshop filters you created please. We want to have a backup for future usage.

New UI
----

Both Hima and Mea.

Note: Need to remake the tips screen.

@InochiPM Do you have everything you need for this?

New DLLs
----

Both Hima and Mea.

@idealpersona If I remember correctly you already started working on these? What's the current progress?

New voice packs
----

All 5 chapters. I have a script ready for this.

**Comment by enumag** [comment]
@irlPM So about the missing sprites...

First part of the problem was that your table for Rena used nonexistent sprites in several cases. I've fixed.

Second part is something I'll need your help with. You remember the problem in Watanagashi where we didn't have the night sprites for Kasai? Well this time we're missing sunset sprites for him.

**Comment by irlPM** [comment]
About the missing CG's, I'll check it out today at night, if the work  is too much for the benefit I think we can leave it and just use the ones we already have.
Here is all the kasai sprites with the sunset filter:
[Kasai.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1867798/Kasai.zip)
The only that changed is sunset, so here it is. 
[Sunset.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/1867782/Sunset.zip)

**Comment by enumag** [comment]
Agreed. The only thing we really need to remake are the brown sprites fo
Oryou.

Dne po 2. 4. 2018 12:01 uživatel irlPM <notifications@github.com> napsal:

**Comment by irlPM** [comment]
After checking the CG's, I agree with you. Could you send me the  brown oryou that you are talking about? To use as a example to made one.

**Comment by idealpersona** [comment]
Glad I happened to see this - I get emails on like every issue so if I get mentioned it's no noisier than any other comment; perhaps I should quiet down those notifications.

Himatsubushi dev is ready for testing:
- Draft DLL is here - note the new branch:  https://github.com/07th-mod/higurashi-dlls/raw/full-lipsync-port/Himatsubushi/Assembly-CSharp.dll
- Documentation here https://github.com/07th-mod/higurashi-patch-compiler/wiki/Lipsync-Development

@enumag @ItaloKnox Beyond this, I need lipsync-ready scripts and assets for Himatsubushi in order to test.  Do we have those ready to go already?  I am having a hard time finding them on my own if so.

**Comment by enumag** [comment]
@irlPM They should be in the zip I linked for you in the first post. If not I'll upload them when I get home.

@idealpersona Yeah I have the same problem with GitHub. Would it help if I send you a link on Discord in such cases? We have the [lip-sync](https://github.com/07th-mod/himatsubushi/tree/lip-sync) branch for in hima repo but it's probably outdated by now. I'll commit the latest version to that branch when I get home.

**Comment by idealpersona** [comment]
Himatsubushi now merged to master. Meakashi is not yet started.

**Comment by idealpersona** [comment]
@enumag Draft Meakashi port now available on master and documentation updated.  Works at a glance without regressions on the existing release but hasn't been tested with any lipsync functionality directly.  Didn't see any Meakashi assets on Hanyuu and neither my installation nor meakashi `lip-sync` branch seems to have lip-sync expression assets, so I imagine those are not yet packaged up?

**Comment by enumag** [comment]
@idealpersona Correct, we don't have Meakashi graphics pack yet. We'll get it done this weekend.

**Comment by enumag** [comment]
@InochiPM Any progress with the text and tips images? I'd like to finish the new Meakashi CG pack but I'm still missing these.
