### ISSUE TITLE
New voice packs for Oni, Wata and Tata

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#39]
@ItaloKnox Time to remake voice packs for the first three chapters. I've spent quite some time tweking these but it should hopefully be easy for you.

You still have the directory structure for voice pack compilation in place I assume? Then you just need these sh scripts and you should be able to compile them: https://www.dropbox.com/s/z1k8o2fbev6pmg4/voices.7z?dl=0

----

For Onikakushi we also need to release new graphics pack with all the sprites orian34 added + new flashback backgrounds from Grelo.

1. Download and unpack current Oni CG and CGAlt from Hanyuu.
2. Delete `CG/append` directory.
3. Merge in files from this archive: https://www.dropbox.com/s/oli2tr6bgrfra3m/oni.7z?dl=0
4. Zip and upload (both CG and CGAlt).

----

Scripts are already updated in the master branches of the chapters. You can make new releases when you're finished.

**Comment by ItaloKnox** [comment]
Onikakushi Voice and Graphics Patch v5.6.0 
<https://github.com/07th-mod/onikakushi/releases/tag/v5.6.0>

Watanagashi Voice and Graphics Patch v4.1.0
<https://github.com/07th-mod/watanagashi/releases/tag/v4.1.0>

Tatarigoroshi Voice and Graphics Patch v5.1.0
<https://github.com/07th-mod/tatarigoroshi/releases/tag/v5.1.0>
