### ISSUE TITLE
Better looking sprites

### ISSUE THREAD

**Issue by Grelo** [07th-mod/higurashi-patch-compiler#4]
I tried to make sprites in 1920x1080 like background images and figured out that they look slightly better in game. I can make AGAIN whole overhaul of sprites for all chapters if you want. If you decide for than teach me how can i add them to our current graphic folders or i need to make folders to download for you again. 

Example: 
Old
![re_se_de_a1](https://user-images.githubusercontent.com/22790067/28727036-db3c0d9c-73c3-11e7-99e2-07ae0599201a.png)

New
![re_se_de_a1](https://user-images.githubusercontent.com/22790067/28727055-f05d9588-73c3-11e7-9119-91a992a4a236.png)

Try to open it in same program and compare. Or try it in game.
Minor difference (blurriness) but it counts i think. Or maybe im seeing things....
If its bad just close the issue.

**Comment by Grelo** [comment]
Ok after second look its almost the same. Im closing it.

**Comment by enumag** [comment]
@Grelo I enlarged them to same size and switched between them for a while to see differences. The **old** one looks better. Significantly.

**Comment by Grelo** [comment]
Ok than close it i have comapred in game but you are probably right,

**Comment by enumag** [comment]
Thanks for the effort though!

**Comment by P-Chang** [comment]
i made comparison in different resolution
near 720p
old
![20170729203423_1](https://user-images.githubusercontent.com/29869319/28744589-18701498-749f-11e7-8de6-e1014ff3d6f1.jpg)
new
![20170729203427_1](https://user-images.githubusercontent.com/29869319/28744592-1f346b6c-749f-11e7-8ad8-a0834dba91ce.jpg)

1080p
old
![20170729203434_1](https://user-images.githubusercontent.com/29869319/28744596-2c3819a8-749f-11e7-8a37-b80e57b34780.jpg)
new
![20170729203439_1](https://user-images.githubusercontent.com/29869319/28744599-351d3f1c-749f-11e7-8221-ba33506cb034.jpg)

2160p
old
![20170729203632_1](https://user-images.githubusercontent.com/29869319/28744600-3eb2b818-749f-11e7-9291-a54e30e6d2df.jpg)
new
![20170729203636_1](https://user-images.githubusercontent.com/29869319/28744602-451b4b02-749f-11e7-9ebd-c02241461ebe.jpg)

**Comment by P-Chang** [comment]
I think new one is really good in virtual 2160p with 1080p monitor(but my rig can't handle it). 
and fit in background. but in zooming, old one win(blur help this).

I like new one in native resolution of my monitor.
After finish it. if we can choice old one or new one, it  is really good.
This mod is VRAM eater than late 2000s 3D games.

And please, don't change aspect ratio and write file name, next time.

**Comment by ItaloKnox** [comment]
I have an IPS monitor so I notice these things immediately and honestly the new sprites are not good going by your comparison. They look too sharp and the colors are definitely wrong. Let's just bury this and move on...
