### ISSUE TITLE
Meakashi LipSync release

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#40]
@ItaloKnox Meakashi LipSync is long overdue so let's get that out as well.

Let me know on Discord when you're about to start. I'm still missing some images when writing this post but they might be ready by the time you read this.

Graphics pack
----

Using the same structure as before which you should have mostly in place (if not let me know):

https://www.dropbox.com/s/ixwxvidbevl1mo2/meakashi.sh?dl=0

```
meakashi-old/
  CG/
  CGAlt/
ps3/
sprites/
  Night/
  Normal/
  Sunset/
meakashi.sh
```

`meakashi.sh` generate a `meakashi` directory with an almost complete pack.

Delete the CGAlt directory, we already have a better one in Hanyuu release.

Then download and merge in these files: https://www.dropbox.com/s/eqqfwh2q4y34jss/Meakashi-CG.7z?dl=0

Also add the windo_filter textboxes into CG directory.

Zip and upload to Hanyuu.

Voice pack
----

Again using the usual structure for voice pack compilation. Here is the script:

https://www.dropbox.com/s/qmxa5blqln7jdnx/meakashi-voices.sh?dl=0

----

Let me know when you're done. I'll use my script to check for any missing files and then we should be able to make a pre-release.

**Comment by ItaloKnox** [comment]
https://github.com/07th-mod/resources/releases/download/Hanyuu/Meakashi-CG.7z
https://github.com/07th-mod/resources/releases/download/Hanyuu/Meakashi-Voices.7z
