### ISSUE TITLE
Fixed UI for all chapters

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#43]
@ItaloKnox We finished and tested the UI for all 5 previous chapters. It contains various fixes for transparency, swapped arrows, moving buttons, typo on config screen etc. There is no reason to release new versions just for new UI but we should soon have other changes ready to roll (movie support for all chapters and new graphics packs for Wata and Tata). Include these when making the new releases.

Also this is the first time we have new UI for Himatsubushi and by extension for the console arcs.

https://www.dropbox.com/s/ibcyh6cz6chii5o/UI%20fixes.7z?dl=0

Credits to @irlPM, @jwgrlrrajn, @InochiPM, @orian34 and @Petsnew who all helped me with this.

**Comment by ItaloKnox** [comment]
Just pushed all of them. Hopefully, I'll never do that again.
