### ISSUE TITLE
Better assets bundle modification

### ISSUE THREAD

**Issue by tellowkrinkle** [07th-mod/higurashi-patch-compiler#49]
@enumag I have a new tool to test, it should allow better automation of asset bundle editing, download it [here](https://gist.github.com/tellowkrinkle/29ff591ad38e001cf6a4e4b2dcca5e16).  Probably still buggy.
Usage:
1. Put all the files you want to edit into a folder with the filename either starting with object's target path ID or in the format `name_type` (for example, `TipsPrefab_Texture2D.png` will target the object named TipsPrefab that is a Texture2D).  Supported formats are raw (`.dat`) and `.png` for Texture2D files.  Example directory listing (the numbered files are text replacements generated by [UnityTextModifier.py](
https://gist.github.com/tellowkrinkle/5f8f45b9fb62356257b46457594654f9)): <img width="313" alt="File Layout Example" src="https://user-images.githubusercontent.com/3315070/44501636-b725bc00-a653-11e8-93e8-8029249986e4.png">
1. Run `python3 EMIPGenerator.py sharedassets0.assets folderName output.emip` to convert all the files into a single emip file.  You will need the packages `numpy`, `Pillow` and `unitypack` installed, install them with `pip3 install numpy Pillow unitypack`
1. In UABE, choose File → Load Package File and select the emip file to apply all the changes at once.  If you're running it in Windows, the full path should (hopefully) be put in, but if it's not, add the folder that the assets file is in to the bottom text box.

EDIT by @enumag: Previous issue about text replacement: https://github.com/07th-mod/higurashi-dlls/issues/18

**Comment by enumag** [comment]
Wow, really? I'll need to install python and test this.

**Comment by enumag** [comment]
Unfortunately I'm unable to unstall the `unitypack` package. It has a dependency on something called `decrunch` and building `decrunch` always fails for me. At first it failed with an error saying to install Visual C++ Build Tools 14.0. After some searching I found the thing, installed it and restared the PC (the installer said it was required).

Now however `decrunch` still can't be installed and this time it's a far less readable error - I tried to google it but without success.

```
Installing collected packages: decrunch, unitypack
  Running setup.py install for decrunch ... error
    Complete output from command c:\users\enumag\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Enumag\\AppData\\Local\\Temp\\pip-install-xcllarnb\\decrunch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Enumag\AppData\Local\Temp\pip-record-yy1u6j9g\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'decrunch' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icrunch -Ic:\users\enumag\appdata\local\programs\python\python37\include -Ic:\users\enumag\appdata\local\programs\python\python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.15.26726\include" /EHsc /Tpcrn_decomp.cpp /Fobuild\temp.win-amd64-3.7\Release\crn_decomp.obj
    crn_decomp.cpp
    crn_decomp.cpp(2): fatal error C1083: Cannot open include file: 'string.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

Any idea what should I do?

**Comment by enumag** [comment]
Note: When installing the Build Toold the installer had a long list of optional things which I did not install. Do you think I need some of the optional things?

![optional](https://user-images.githubusercontent.com/539462/44543402-b8b4ba00-a70f-11e8-8b90-7338b82ef6cc.png)

**Comment by tellowkrinkle** [comment]
That stupid decrunch dependency keeps breaking (the published version broke on Mac as well so I had to download the package directly)

It's only used for a part of the library that we're not using so [here's a fork of the library that removes it](https://github.com/tellowkrinkle/UnityPack).  Download that and run `python3 setup.py install`

**Comment by enumag** [comment]
Thanks that worked, I can run the script now. As you expected it seems it's a little buggy:

```
WARNING:root:-32 absent from structs.dat
WARNING:root:-4 absent from structs.dat
WARNING:root:-47 absent from structs.dat
WARNING:root:-12 absent from structs.dat
WARNING:root:-30 absent from structs.dat
WARNING:root:-23 absent from structs.dat
WARNING:root:-42 absent from structs.dat
WARNING:root:-45 absent from structs.dat
WARNING:root:-20 absent from structs.dat
WARNING:root:-15 absent from structs.dat
WARNING:root:-16 absent from structs.dat
WARNING:root:-11 absent from structs.dat
WARNING:root:-9 absent from structs.dat
WARNING:root:-7 absent from structs.dat
WARNING:root:-8 absent from structs.dat
WARNING:root:-13 absent from structs.dat
WARNING:root:-3 absent from structs.dat
WARNING:root:-46 absent from structs.dat
WARNING:root:-39 absent from structs.dat
WARNING:root:-36 absent from structs.dat
WARNING:root:-29 absent from structs.dat
WARNING:root:-35 absent from structs.dat
WARNING:root:-28 absent from structs.dat
WARNING:root:-37 absent from structs.dat
WARNING:root:-54 absent from structs.dat
WARNING:root:-18 absent from structs.dat
WARNING:root:-2 absent from structs.dat
WARNING:root:-41 absent from structs.dat
WARNING:root:-52 absent from structs.dat
WARNING:root:-49 absent from structs.dat
WARNING:root:-10 absent from structs.dat
WARNING:root:-21 absent from structs.dat
WARNING:root:-55 absent from structs.dat
WARNING:root:-48 absent from structs.dat
WARNING:root:-5 absent from structs.dat
WARNING:root:-26 absent from structs.dat
WARNING:root:-51 absent from structs.dat
WARNING:root:-25 absent from structs.dat
WARNING:root:-38 absent from structs.dat
WARNING:root:-50 absent from structs.dat
WARNING:root:-22 absent from structs.dat
WARNING:root:-53 absent from structs.dat
WARNING:root:-31 absent from structs.dat
WARNING:root:-33 absent from structs.dat
WARNING:root:-34 absent from structs.dat
WARNING:root:-40 absent from structs.dat
WARNING:root:-24 absent from structs.dat
WARNING:root:-17 absent from structs.dat
WARNING:root:-27 absent from structs.dat
WARNING:root:-6 absent from structs.dat
WARNING:root:-44 absent from structs.dat
WARNING:root:-14 absent from structs.dat
WARNING:root:-19 absent from structs.dat
WARNING:root:-43 absent from structs.dat
Will replace object #20 with contents of Backlog_Texture2D.png converted to a Texture2D
Will replace object #22 with contents of black_Texture2D.png converted to a Texture2D
Will replace object #21 with contents of ChapterPreview_Texture2D.png converted to a Texture2D
Will replace object #42 with contents of configbg_jp_Texture2D.png converted to a Texture2D
Will replace object #36 with contents of configbg_Texture2D.png converted to a Texture2D
Will replace object #23 with contents of ConfigHigurashi_Texture2D.png converted to a Texture2D
Traceback (most recent call last):
  File "./EMIPGenerator.py", line 142, in <module>
    edit.getAssetInfo(assets, bundle)
  File "./EMIPGenerator.py", line 71, in getAssetInfo
    if obj.type != self.type: continue
  File "C:\Users\Enumag\AppData\Local\Programs\Python\Python37\lib\site-packages\unitypack-0.9.0-py3.7.egg\unitypack\object.py", line 30, in type
    script = self.read()["m_Script"]
  File "C:\Users\Enumag\AppData\Local\Programs\Python\Python37\lib\site-packages\unitypack-0.9.0-py3.7.egg\unitypack\object.py", line 84, in read
    return self.read_value(self.type_tree, BinaryReader(BytesIO(object_buf)))
  File "C:\Users\Enumag\AppData\Local\Programs\Python\Python37\lib\site-packages\unitypack-0.9.0-py3.7.egg\unitypack\object.py", line 51, in type_tree
    return TypeMetadata.default(self.asset).type_trees[self.class_id]
KeyError: -32
```

The emip file did not appear either. I'll retry later with fewer images.

**Comment by tellowkrinkle** [comment]
What did you call it with?

**Comment by enumag** [comment]
On my PC there is no python3 command so I used python command instead. That should be ok, right? 

Here is the command and the files I used.

```
python ./EMIPGenerator.py ./tsumi-assets-working/sharedassets0.assets ./tsumi-images tsumi.emip
```

[Python tool experiment.zip](https://github.com/07th-mod/higurashi-patch-compiler/files/2315920/Python.tool.experiment.zip)

**Comment by tellowkrinkle** [comment]
Yeah that should be fine (`python3` is generally the name of version 3 of the `python` executable on computers that come preinstalled with python 2 which includes Macs and Ubuntu, other computers will just install it as `python`)
Let me see if I can reproduce this

**Comment by enumag** [comment]
Oh sorry there was one file that was missing the `_Texture2D` suffix. It works fine after I fixed that. Some better error message would be nice though.

**Comment by enumag** [comment]
It still throws a little error at the end:

```
Object #20 / Backlog is of a currently unsupported image format (4)
Traceback (most recent call last):
  File "./EMIPGenerator.py", line 150, in <module>
    outputFile.write(edit.bytes)
  File "./EMIPGenerator.py", line 104, in bytes
    out += len(fileBytes).to_bytes(4, byteorder='little') # Payload Size
TypeError: object of type 'NoneType' has no len()
```

But I'm a bit confused because at the beginning there was this line about the Backlog image:

```
Will replace object #20 with contents of Backlog_Texture2D.png converted to a Texture2D
```

Anyway I got the emip file so I'll try to do the next step.

**Comment by tellowkrinkle** [comment]
Hm that's weird.  What was its name?

The `WARNING:root absent from structs.dat` appears to be some issue with Tsumi's `.assets` file not working very well with UnityPack.

Oh I just realized that I write the file as I go, if you get that error it won't have made the whole emip file (so it probably won't work) but I do know what that's caused by (I only ever saw image format 5 in the ones I was working with so I only set up support for that.)  Let me add support for format 4 as well.

**Comment by enumag** [comment]
Hmm actually the emip file is empty. So I guess it first went through the images to plan what to replace and only then tried to generate the emip file which failed on the first images. Anyway I sent you the files earlier so you should be able to reproduce it I think?

**Comment by tellowkrinkle** [comment]
That second error is one written by me (and not thrown by UnityPack) so I know what caused it

**Comment by enumag** [comment]
What is that image format 4 / 5 / whatever anyway?

**Comment by tellowkrinkle** [comment]
It's the format of the image stored in the asset bundle (and therefore what I try to convert the PNG to), you can look up what they correspond to [here](https://github.com/HearthSim/UnityPack/blob/master/unitypack/engine/texture.py)

**Comment by tellowkrinkle** [comment]
Alright see if [this](https://gist.github.com/tellowkrinkle/29ff591ad38e001cf6a4e4b2dcca5e16) works

**Comment by enumag** [comment]
For reference, the latest scripts are now in this repo: https://github.com/07th-mod/ui-editing-scripts

Documentation will be added here: https://github.com/07th-mod/higurashi-dev-guides/wiki/UI-editing-scripts
