### ISSUE TITLE
Tips Menu and UI editing.

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/higurashi-patch-compiler#5]
Unity Assets Bundle Extractor works with Higurashi assets file.
https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor

Changing tips thumbnail and background and UI is possible.

but these aspect ratio are really protected by material(?)

sample: it is just test so it is really ugly.
![20170729120244_1](https://user-images.githubusercontent.com/29869319/28742195-82d780b8-7464-11e7-9b12-0398feb8b094.jpg)
![20170729133620_1](https://user-images.githubusercontent.com/29869319/28742199-87943ec0-7464-11e7-9a04-db7782c56aa2.jpg)
![abi](https://user-images.githubusercontent.com/29869319/28742202-9431c9f4-7464-11e7-8a7f-03ac9851984f.png)

**Comment by enumag** [comment]
So the aspect ratio can't be fixed?

**Comment by P-Chang** [comment]
For now, yes. but I thought GUI Pos can be fixed. it might be just my overlooking.
But these have really many components. so it may be so hard to editing, even if I find way.
