### ISSUE TITLE
Major audio update (all chapters)

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/higurashi-patch-compiler#55]
This is a rather complex issue, so I hope to compile all information in a single place we can discuss it further.

## The update

Today (April 1st, 2019), a new update was released for all chapters of the game. This update replaces music and sound effects. As far as we know, not everything was replaced by new SFX or music, but it seems like all of them had some kind of remake (minor or major).

## The issue

Looks like this update is a hit or miss. The community seems to be annoyed by it because it replaces some of the good aspects with the game with worse audio in general. To make it even worse, some aspects of it are also good, so, unfortunately, there is no exact middle ground where we can build upon. Mileage will vary accordingly to your tastes in audio.

## The solution

Here are some of the solutions condensed in a few checkmarks. Those marked are certain to be happening, others are up to discussion.

* [x] Separate SFX and music packs are going to be made to allow users to rollback to old audio if they want
* [x] The new python installer will receive a new option to install rollback packs (and extra stuff) optionally
* [ ] Create a curated pack of SFX and music based on what the community seems to agree that is best
    * I don't exactly like this because we can never make everyone happy. This can be way too hard to maintain and can fuel issues we don't need.

## Some drawbacks

* Looks like the Answer Arcs, in general, had a few changes in the script that might be bothersome if we plan to rollback.
    * Still looking into it
* Every chapter from Ch.7 onwards cannot be easily rolled back because they are not released yet. When they come out, they will have the new audio. That means we will have to manually work through the original NScripter version in japanese to find out the audio used.
    * Of course, that supposing new chapters will use a different naming scheme instead or simple overwrites like the first six chapters.

## Extra stuff

* Naegles kindly shared some handmade packs we can use as a reference. [Link here.](https://drive.google.com/drive/folders/1IoKsqgdYkkBpfgYJV6-jfUl5wxMxstQp)

### Getting previous depots (aka versions)

O[A] also kindly shared a small tutorial on how to pull the previous versions of the game directly from Steam:

```
I'll also put this here just in case you ever need a reliable place for getting the old OSTs.
Here are the commands:
download_depot 310360 310361 4410936638386498651 for Onikakushi
download_depot 410890 410891 6649378427451771594 for Watanagashi
download_depot 472870 472871 224693427286909718 for Tatarigoroshi
download_depot 526490 526491 3512022933343269940 for Himatsubushi
download_depot 577480 577481 1418629749600637923 for Mekashi
download_depot 668350 668351 5429542121950713111 for Tsumihoroboshi
Type these into the Steam console. To open that, hit Win+R and then type steam://open/console
There will be no progress indication for the download and it won't automatically replace the existing version of the game
```

**Comment by Kamukura1337** [comment]
Since there was another patch fixing the bugs we mentioned to day I updated the document and the packs I made accordingly. It's all in this google drive now 
https://drive.google.com/drive/folders/1IoKsqgdYkkBpfgYJV6-jfUl5wxMxstQp (same link as above)

**Comment by enumag** [comment]
> Create a curated pack of SFX and music based on what the community seems to agree that is best
> I don't exactly like this because we can never make everyone happy. This can be way too hard to maintain and can fuel issues we don't need.

I talked about @irlPM privately and after the conversation I think we should make such pack. There is no need to try to make everyone happy, let's just call it the "07th-mod audio pack" and pick whatever we prefer - no need to take community suggestions, if someone disagrees they can change it themselves. It is also a good opportunity to include all of your remastered songs. As Irl pointed out, it's a shame that noone outside of the dev team knows they exist.

**Comment by ItaloKnox** [comment]
That works great, my plan was to separate small packs (just a few replacements) from big packs (complete changes), but I can give the option to install my remakes only if the user decides to keep the new music or install the old music over it. Otherwise, just leave it there as the default. We should try to decide what we think it's best, I will try to look into it tomorrow and compile a list of what I liked and disliked.

**Comment by drojf** [comment]
I'm closing this issue as the information is very out of date. The issue will still be linked from the new **"[BGM & SE Issues Index ](https://github.com/07th-mod/higurashi-patch-compiler/issues/64)"**
