### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#7]
@P-chang The first bug is on the save screen - it does not work well with colors and sizes which we use in ADV-mode. Can you somehow remove the names and tags from the save file titles?

https://www.dropbox.com/s/sky4f6nlrun1lhe/save%20edited.png?dl=0

Second bug is icons positioning. Normally the icons are positioned like this:

https://www.dropbox.com/s/llhz9bg8xct6wm3/icons.png?dl=0

I can move the icons and the text to the right using `SetGUIPosition(170, 0);` in init.txt and then move the text back using `SetWindowPos(-170, 0);`. But it causes this issue with line end icons:

https://www.dropbox.com/s/txs8utatvbrqh31/icons%20edited.png?dl=0

Can you do something about these? I have no idea if these are even handled by the DLL you're working on. If it's impossible, just let me know.

**Comment by P-Chang** [comment]
Hmm, I'll try but please don’t expect too much.

**Comment by enumag** [comment]
I actually don't. I suspect the first problem should be easy to fix by a regular expression somewhere in the saving logic - and I already know you're capable of writing regexps. Second problem is caused by the fact that the game is originally 4:3 and our patch changes it to 16:9 so it should be fixed by changing or adding a constant somewhere in the positioning logic. Finding the right places however could be very difficult if not impossible. Either way, thanks for looking into it!

**Comment by P-Chang** [comment]
Second one was not difficult as much as we thought.
I have found a way to fix waiting icon positions (but I should find better logic)
http://www.mediafire.com/file/nw2ga70n4rjq131/Assembly-CSharp.dll (it is chapter 5 dlls)

please test many position, I've not understood why it works, and I don't know it works corretly in any position.

I can't understand that Y vector could be change in vanilla but X vector couldn't.
I hope it is only bug or devs just forget.

Probably, fix first one is not difficult, but find correct location is really insane.
There are ton of class and method that is named save*** or load***

**Comment by enumag** [comment]
It seems to work fine. I didn't tast many different positions but I don't think we need to - we don't want the icons anywhere else than bottom right.

The only issue I found was the positioning being quite broken when I go full screen on a 16:10 monitor. It was better after restarting the game although the icons were off-screen. However this would probably be very difficult to fix and I don't think it's worth it. The initially broken positioning is fixed by restart and if anyone reports a bug with off-screen icons we can just tell them to adjust the SetGUIPosition in init.txt.

As for the other features you added previously I could not find any bugs, everything seems fine. The only thing I think we could adjust is the F10 screen - currently it goes in a cycle through 4 different screens I think? We could reduce it. Like when another press just adds a second column and the first column stays the same we could simply show both columns on first press.

Thanks for fixing the icons! Some people (@Grelo was one of them if I remember correctly) like to have them visible all the time so this will certainly help.

**Comment by P-Chang** [comment]
Right? could you upload screenshot with 16:10?
My sub monitor is 4:3, I know nearly things with this or other dll.

In user mode, flag monitor is only 2. I don't think reducing is necessary.
I'll remade this in later(when I made new feature for it).

**Comment by enumag** [comment]
Here is how the game looks normally. It looks the same if I go full screen on 16:9 monitor:

![normal](https://user-images.githubusercontent.com/539462/31055600-9b998748-a6c5-11e7-9083-e6601a9f48fd.png)

But if I go full screen on 16:10 monitor then the text is misplaces, CG is cut, icons overlow:

![tata_16_10_1](https://user-images.githubusercontent.com/539462/31055614-cfe810fa-a6c5-11e7-9fbe-73ff3f77e314.png)

Strangely enough if I close the game while fullscreen on 16:10 and start it again it is partially fixed (icons still overflow):

![tata_16_10_2](https://user-images.githubusercontent.com/539462/31055622-ff2d8552-a6c5-11e7-8891-6f7b8a680c00.png)

------

Any progrss with the save & load screen issue?

**Comment by P-Chang** [comment]
Hmm, it is same as i know.

Probably save&load issue is fixed in DLL that include Line_* fix.

**Comment by enumag** [comment]
Indeed it is fixed. I should have checked before asking you. Thanks!

Should I close this or do you want to look into the aspect ratio issues?

**Comment by P-Chang** [comment]
Honestly, Editing it is scary. I'll edit it in future, but I'll forget it now.
