### ISSUE TITLE
DLL links

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#8]
@P-Chang Quite often I have an issue of not being able to find the right DLL version or finding more than one in your comments and not being sure which I should use. I'd like to ask you to post links to the latest DLLs to this issue. And if you make an update, post it here as well (ideally with a short comment what it adds).

Right now I need the correct DLL for Tata. You were working on some magic to make `WaitToFinishVoicePlaying` not mandatory, right? I can't find that version anywhere though.

**Comment by P-Chang** [comment]
Line_* command fix for Tata is this.
http://www.mediafire.com/file/mmktlsdtl8zd68h/WaitTestChapter3.rar

**Comment by P-Chang** [comment]
Update[2017-10-5]

Fix Line_Continue
Fix Loading Screen can't show ADV Mode Dialog correctly.
Fix Minor small hotkey issues

http://www.mediafire.com/file/4rt313dr8trawt4/chapter1dlls_v3XX.rar
http://www.mediafire.com/file/tihp2mlwqu10c1o/chapter2dlls_v2.x.x.rar
http://www.mediafire.com/file/ab9qvao3o3jp1b5/chapter3dlls_v3.x.x.rar
http://www.mediafire.com/file/tf014pqm25frrnh/chapter4dlls_v.2.x.x.rar
http://www.mediafire.com/file/z8xpnbzasjrdvgk/chapter5dlls_v2.x.x.rar

**Comment by P-Chang** [comment]
Update[2017-10-9]

Added wait time in Line_Continue 

http://www.mediafire.com/file/4rt313dr8trawt4/chapter1dlls_v3XX.rar
http://www.mediafire.com/file/tihp2mlwqu10c1o/chapter2dlls_v2.x.x.rar
http://www.mediafire.com/file/ab9qvao3o3jp1b5/chapter3dlls_v3.x.x.rar
http://www.mediafire.com/file/tf014pqm25frrnh/chapter4dlls_v.2.x.x.rar
http://www.mediafire.com/file/z8xpnbzasjrdvgk/chapter5dlls_v2.x.x.rar
